import { Locale, LocaleConfig } from '@/types';

export const API_KEY = '2f7fe54b-c21b-4d64-b381-e86a738dd4c7';
export const API_BASE_URL = 'https://api.pokemontcg.io/v2';

export const LOCALES: Record<Locale, LocaleConfig> = {
  en: { currency: 'USD', symbol: '$', rate: 1, name: 'English' },
  cs: { currency: 'CZK', symbol: 'Kč', rate: 23.25, name: 'Čeština' },
  sk: { currency: 'EUR', symbol: '€', rate: 0.92, name: 'Slovenčina' },
  jp: { currency: 'JPY', symbol: '¥', rate: 157, name: '日本語' },
};

export const TRANSLATIONS: Record<Locale, Record<string, string>> = {
  en: {
    title: 'POKECOST - Price Tracker',
    home: 'Home',
    myCollection: 'My Collection',
    searchByName: 'Search by name...',
    search: 'Search',
    filterBySet: 'Filter by Set',
    allSets: 'All Sets',
    filterByRarity: 'Filter by Rarity',
    allRarities: 'All Rarities',
    filterByType: 'Filter by Type',
    allTypes: 'All Types',
    addToCollection: 'Add to Collection',
    removeFromCollection: 'Remove from Collection',
    collectionValue: 'Total Collection Value',
    noCardsFound: 'No cards found. Try adjusting your filters.',
    loading: 'Loading...',
    marketPrice: 'Market Price',
    priceNotAvailable: 'N/A',
    emptyCollection: 'Your collection is empty. Start by adding cards from the Home page!',
    clearFilters: 'Clear filters',
    cardsFound: 'cards found',
  },
  cs: {
    title: 'POKECOST - Sledování cen',
    home: 'Domů',
    myCollection: 'Moje sbírka',
    searchByName: 'Hledat podle jména...',
    search: 'Hledat',
    filterBySet: 'Filtrovat podle sady',
    allSets: 'Všechny sady',
    filterByRarity: 'Filtrovat podle vzácnosti',
    allRarities: 'Všechny vzácnosti',
    filterByType: 'Filtrovat podle typu',
    allTypes: 'Všechny typy',
    addToCollection: 'Přidat do sbírky',
    removeFromCollection: 'Odebrat ze sbírky',
    collectionValue: 'Celková hodnota sbírky',
    noCardsFound: 'Nebyly nalezeny žádné karty. Zkuste upravit své filtry.',
    loading: 'Načítání...',
    marketPrice: 'Tržní cena',
    priceNotAvailable: 'N/A',
    emptyCollection: 'Vaše sbírka je prázdná. Začněte přidáním karet z domovské stránky!',
    clearFilters: 'Vyčistit filtry',
    cardsFound: 'nalezených karet',
  },
  sk: {
    title: 'POKECOST - Sledovanie cien',
    home: 'Domov',
    myCollection: 'Moja zbierka',
    searchByName: 'Hľadať podľa mena...',
    search: 'Hľadať',
    filterBySet: 'Filtrovať podľa sady',
    allSets: 'Všetky sady',
    filterByRarity: 'Filtrovať podľa vzácnosti',
    allRarities: 'Všetky vzácnosti',
    filterByType: 'Filtrovať podľa typu',
    allTypes: 'Všetky typy',
    addToCollection: 'Pridať do zbierky',
    removeFromCollection: 'Odobrať zo zbierky',
    collectionValue: 'Celková hodnota zbierky',
    noCardsFound: 'Nenašli sa žiadne karty. Skúste upraviť filtre.',
    loading: 'Načítava sa...',
    marketPrice: 'Trhová cena',
    priceNotAvailable: 'N/A',
    emptyCollection: 'Vaša zbierka je prázdna. Začnite pridávaním kariet z domovskej stránky!',
    clearFilters: 'Vyčistiť filtre',
    cardsFound: 'nájdených kariet',
  },
  jp: {
    title: 'POKECOST - 価格トラッカー',
    home: 'ホーム',
    myCollection: 'マイコレクション',
    searchByName: '名前で検索...',
    search: '検索',
    filterBySet: 'セットで絞り込み',
    allSets: 'すべてのセット',
    filterByRarity: 'レアリティで絞り込み',
    allRarities: 'すべてのレアリティ',
    filterByType: 'タイプで絞り込み',
    allTypes: 'すべてのタイプ',
    addToCollection: 'コレクションに追加',
    removeFromCollection: 'コレクションから削除',
    collectionValue: 'コレクション総額',
    noCardsFound: 'カードが見つかりませんでした。フィルターを調整してください。',
    loading: '読み込み中...',
    marketPrice: '市場価格',
    priceNotAvailable: 'N/A',
    emptyCollection: 'コレクションは空です。ホームページからカードを追加してください。',
    clearFilters: 'フィルターをクリア',
    cardsFound: '枚のカードが見つかりました',
  },
};
