import { Locale, LocaleConfig } from './types';

export const API_KEY = '2f7fe54b-c21b-4d64-b381-e86a738dd4c7';
export const API_BASE_URL = 'https://api.pokemontcg.io/v2';

export const LOCALES: Record<Locale, LocaleConfig> = {
  en: { currency: 'USD', symbol: '$', rate: 1, name: 'English' },
  cs: { currency: 'CZK', symbol: 'Kč', rate: 23.25, name: 'Čeština' },
  sk: { currency: 'EUR', symbol: '€', rate: 0.92, name: 'Slovenčina' },
  jp: { currency: 'JPY', symbol: '¥', rate: 157, name: '日本語' },
};

export const TRANSLATIONS: Record<Locale, Record<string, string>> = {
  en: {
    title: 'POKECOST - Price Tracker',
    home: 'Home',
    myCollection: 'My Collection',
    login: 'Login',
    logout: 'Logout',
    searchByName: 'Search by name...',
    search: 'Search',
    filterBySet: 'Filter by Set',
    allSets: 'All Sets',
    filterByRarity: 'Filter by Rarity',
    allRarities: 'All Rarities',
    filterByType: 'Filter by Type',
    allTypes: 'All Types',
    addToCollection: 'Add to Collection',
    removeFromCollection: 'Remove from Collection',
    removeAll: 'Remove All',
    collectionValue: 'Total Collection Value',
    noCardsFound: 'No cards found. Try adjusting your filters.',
    loading: 'Loading...',
    rarity: 'Rarity',
    type: 'Type',
    set: 'Set',
    marketPrice: 'Market Price',
    loginToManage: 'Login to manage your collection',
    username: 'Email',
    password: 'Password',
    welcome: 'Welcome',
    emptyCollection: 'Your collection is empty. Start by adding cards from the Home page!',
    priceNotAvailable: 'N/A',
    register: 'Register',
    confirmPassword: 'Confirm Password',
    passwordsDoNotMatch: 'Passwords do not match.',
    usernameTaken: 'Username is already taken.',
    invalidCredentials: 'Invalid username or password.',
    alreadyHaveAccount: 'Already have an account? Login',
    dontHaveAccount: "Don't have an account? Register",
    international: 'ENGLISH SETS',
    japan: 'JAPAN SETS',
    'auth/invalid-email': 'Please enter a valid email.',
    'auth/invalid-credential': 'Incorrect email or password.',
    'auth/email-already-in-use': 'An account with this email already exists.',
    'auth/weak-password': 'Password must be at least 6 characters.',
  },
  cs: {
    title: 'POKECOST - Sledování Cen',
    home: 'Domů',
    myCollection: 'Moje Sbírka',
    login: 'Přihlásit se',
    logout: 'Odhlásit se',
    searchByName: 'Hledat podle jména...',
    search: 'Hledat',
    filterBySet: 'Filtrovat podle Sady',
    allSets: 'Všechny Sady',
    filterByRarity: 'Filtrovat podle Vzácnosti',
    allRarities: 'Všechny Vzácnosti',
    filterByType: 'Filtrovat podle Typu',
    allTypes: 'Všechny Typy',
    addToCollection: 'Přidat do Sbírky',
    removeFromCollection: 'Odebrat ze Sbírky',
    removeAll: 'Odebrat Všechny',
    collectionValue: 'Celková Hodnota Sbírky',
    noCardsFound: 'Nebyly nalezeny žádné karty. Zkuste upravit filtry.',
    loading: 'Načítání...',
    rarity: 'Vzácnost',
    type: 'Typ',
    set: 'Sada',
    marketPrice: 'Tržní Cena',
    loginToManage: 'Přihlaste se pro správu své sbírky',
    username: 'E-mail',
    password: 'Heslo',
    welcome: 'Vítejte',
    emptyCollection: 'Vaše sbírka je prázdná. Začněte přidáváním karet z domovské stránky!',
    priceNotAvailable: 'N/A',
    register: 'Registrovat',
    confirmPassword: 'Potvrdit heslo',
    passwordsDoNotMatch: 'Hesla se neshodují.',
    usernameTaken: 'Uživatelské jméno je již obsazeno.',
    invalidCredentials: 'Nesprávné uživatelské jméno nebo heslo.',
    alreadyHaveAccount: 'Máte již účet? Přihlaste se',
    dontHaveAccount: 'Nemáte účet? Registrujte se',
    international: 'ANGLICKÉ SADY',
    japan: 'JAPONSKÉ SADY',
    'auth/invalid-email': 'Zadejte prosím platný e-mail.',
    'auth/invalid-credential': 'Nesprávný e-mail nebo heslo.',
    'auth/email-already-in-use': 'Účet s tímto e-mailem již existuje.',
    'auth/weak-password': 'Heslo musí mít alespoň 6 znaků.',
  },
  sk: {
    title: 'POKECOST - Sledovanie Cien',
    home: 'Domov',
    myCollection: 'Moja Zbierka',
    login: 'Prihlásiť sa',
    logout: 'Odhlásiť sa',
    searchByName: 'Hľadať podľa mena...',
    search: 'Hľadať',
    filterBySet: 'Filtrovať podľa Sady',
    allSets: 'Všetky Sady',
    filterByRarity: 'Filtrovať podľa Vzácnosti',
    allRarities: 'Všetky Vzácnosti',
    filterByType: 'Filtrovať podľa Typu',
    allTypes: 'Všetky Typy',
    addToCollection: 'Pridať do Zbierky',
    removeFromCollection: 'Odobrať zo Zbierky',
    removeAll: 'Odstrániť Všetky',
    collectionValue: 'Celková Hodnota Zbierky',
    noCardsFound: 'Nenašli sa žiadne karty. Skúste upraviť filtre.',
    loading: 'Načítava sa...',
    rarity: 'Vzácnosť',
    type: 'Typ',
    set: 'Sada',
    marketPrice: 'Trhová Cena',
    loginToManage: 'Prihláste sa pre správu svojej zbierky',
    username: 'E-mail',
    password: 'Heslo',
    welcome: 'Vitajte',
    emptyCollection: 'Vaša zbierka je prázdna. Začnite pridávaním kariet z domovskej stránky!',
    priceNotAvailable: 'N/A',
    register: 'Registrovať',
    confirmPassword: 'Potvrdiť heslo',
    passwordsDoNotMatch: 'Heslá sa nezhodujú.',
    usernameTaken: 'Používateľské meno je už obsadené.',
    invalidCredentials: 'Nesprávne používateľské meno alebo heslo.',
    alreadyHaveAccount: 'Máte už účet? Prihláste sa',
    dontHaveAccount: 'Nemáte účet? Zaregistrujte sa',
    international: 'ANGLICKÉ SADY',
    japan: 'JAPONSKÉ SADY',
    'auth/invalid-email': 'Zadajte, prosím, platný e-mail.',
    'auth/invalid-credential': 'Nesprávny e-mail alebo heslo.',
    'auth/email-already-in-use': 'Účet s týmto e-mailom už existuje.',
    'auth/weak-password': 'Heslo musí mať aspoň 6 znakov.',
  },
  jp: {
    title: 'POKECOST - 価格トラッカー',
    home: 'ホーム',
    myCollection: 'マイコレクション',
    login: 'ログイン',
    logout: 'ログアウト',
    searchByName: '名前で検索...',
    search: '検索',
    filterBySet: 'セットで絞り込み',
    allSets: 'すべてのセット',
    filterByRarity: 'レアリティで絞り込み',
    allRarities: 'すべてのレアリティ',
    filterByType: 'タイプで絞り込み',
    allTypes: 'すべてのタイプ',
    addToCollection: 'コレクションに追加',
    removeFromCollection: 'コレクションから削除',
    removeAll: 'すべて削除',
    collectionValue: 'コレクション総額',
    noCardsFound: 'カードが見つかりませんでした。フィルターを調整してください。',
    loading: '読み込み中...',
    rarity: 'レアリティ',
    type: 'タイプ',
    set: 'セット',
    marketPrice: '市場価格',
    loginToManage: 'コレクションを管理するにはログインしてください',
    username: 'メールアドレス',
    password: 'パスワード',
    welcome: 'ようこそ',
    emptyCollection: 'コレクションは空です。ホームページからカードを追加してみましょう！',
    priceNotAvailable: 'N/A',
    register: '登録',
    confirmPassword: 'パスワードを再入力',
    passwordsDoNotMatch: 'パスワードが一致しません。',
    usernameTaken: 'このユーザー名は既に使用されています。',
    invalidCredentials: 'ユーザー名またはパスワードが無効です。',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？ログイン',
    dontHaveAccount: 'アカウントをお持ちでないですか？登録',
    international: '英語セット',
    japan: '日本語セット',
    'auth/invalid-email': '有効なメールアドレスを入力してください。',
    'auth/invalid-credential': 'メールアドレスまたはパスワードが正しくありません。',
    'auth/email-already-in-use': 'このメールアドレスは既に使用されています。',
    'auth/weak-password': 'パスワードは6文字以上で設定してください。',
  },
};