import { Locale, LocaleConfig } from './types';

export const API_KEY = '2f7fe54b-c21b-4d64-b381-e86a738dd4c7';
export const API_BASE_URL = 'https://api.pokemontcg.io/v2';

export const LOCALES: Record<Locale, LocaleConfig> = {
  en: { currency: 'USD', symbol: '$', rate: 1, name: 'English' },
  cs: { currency: 'CZK', symbol: 'Kč', rate: 23.25, name: 'Čeština' },
  sk: { currency: 'EUR', symbol: '€', rate: 0.92, name: 'Slovenčina' },
};

export const TRANSLATIONS: Record<Locale, Record<string, string>> = {
  en: {
    title: 'POKECOST - Price Tracker',
    home: 'Home',
    myCollection: 'My Collection',
    login: 'Login',
    logout: 'Logout',
    searchByName: 'Search by name...',
    search: 'Search',
    filterBySet: 'Filter by Set',
    allSets: 'All Sets',
    filterByRarity: 'Filter by Rarity',
    allRarities: 'All Rarities',
    filterByType: 'Filter by Type',
    allTypes: 'All Types',
    addToCollection: 'Add to Collection',
    removeFromCollection: 'Remove from Collection',
    removeAll: 'Remove All',
    collectionValue: 'Total Collection Value',
    noCardsFound: 'No cards found. Try adjusting your filters.',
    loading: 'Loading...',
    rarity: 'Rarity',
    type: 'Type',
    set: 'Set',
    marketPrice: 'Market Price',
    loginToManage: 'Login to manage your collection',
    username: 'Username',
    password: 'Password',
    welcome: 'Welcome',
    emptyCollection: 'Your collection is empty. Start by adding cards from the Home page!',
    priceNotAvailable: 'N/A',
    register: 'Register',
    confirmPassword: 'Confirm Password',
    passwordsDoNotMatch: 'Passwords do not match.',
    usernameTaken: 'Username is already taken.',
    invalidCredentials: 'Invalid username or password.',
    alreadyHaveAccount: 'Already have an account? Login',
    dontHaveAccount: "Don't have an account? Register",
  },
  cs: {
    title: 'POKECOST - Sledování Cen',
    home: 'Domů',
    myCollection: 'Moje Sbírka',
    login: 'Přihlásit se',
    logout: 'Odhlásit se',
    searchByName: 'Hledat podle jména...',
    search: 'Hledat',
    filterBySet: 'Filtrovat podle Sady',
    allSets: 'Všechny Sady',
    filterByRarity: 'Filtrovat podle Vzácnosti',
    allRarities: 'Všechny Vzácnosti',
    filterByType: 'Filtrovat podle Typu',
    allTypes: 'Všechny Typy',
    addToCollection: 'Přidat do Sbírky',
    removeFromCollection: 'Odebrat ze Sbírky',
    removeAll: 'Odebrat Všechny',
    collectionValue: 'Celková Hodnota Sbírky',
    noCardsFound: 'Nebyly nalezeny žádné karty. Zkuste upravit filtry.',
    loading: 'Načítání...',
    rarity: 'Vzácnost',
    type: 'Typ',
    set: 'Sada',
    marketPrice: 'Tržní Cena',
    loginToManage: 'Přihlaste se pro správu své sbírky',
    username: 'Uživatelské jméno',
    password: 'Heslo',
    welcome: 'Vítejte',
    emptyCollection: 'Vaše sbírka je prázdná. Začněte přidáváním karet z domovské stránky!',
    priceNotAvailable: 'N/A',
    register: 'Registrovat',
    confirmPassword: 'Potvrdit heslo',
    passwordsDoNotMatch: 'Hesla se neshodují.',
    usernameTaken: 'Uživatelské jméno je již obsazeno.',
    invalidCredentials: 'Nesprávné uživatelské jméno nebo heslo.',
    alreadyHaveAccount: 'Máte již účet? Přihlaste se',
    dontHaveAccount: 'Nemáte účet? Registrujte se',
  },
  sk: {
    title: 'POKECOST - Sledovanie Cien',
    home: 'Domov',
    myCollection: 'Moja Zbierka',
    login: 'Prihlásiť sa',
    logout: 'Odhlásiť sa',
    searchByName: 'Hľadať podľa mena...',
    search: 'Hľadať',
    filterBySet: 'Filtrovať podľa Sady',
    allSets: 'Všetky Sady',
    filterByRarity: 'Filtrovať podľa Vzácnosti',
    allRarities: 'Všetky Vzácnosti',
    filterByType: 'Filtrovať podľa Typu',
    allTypes: 'Všetky Typy',
    addToCollection: 'Pridať do Zbierky',
    removeFromCollection: 'Odobrať zo Zbierky',
    removeAll: 'Odstrániť Všetky',
    collectionValue: 'Celková Hodnota Zbierky',
    noCardsFound: 'Nenašli sa žiadne karty. Skúste upraviť filtre.',
    loading: 'Načítava sa...',
    rarity: 'Vzácnosť',
    type: 'Typ',
    set: 'Sada',
    marketPrice: 'Trhová Cena',
    loginToManage: 'Prihláste sa pre správu svojej zbierky',
    username: 'Používateľské meno',
    password: 'Heslo',
    welcome: 'Vitajte',
    emptyCollection: 'Vaša zbierka je prázdna. Začnite pridávaním kariet z domovskej stránky!',
    priceNotAvailable: 'N/A',
    register: 'Registrovať',
    confirmPassword: 'Potvrdiť heslo',
    passwordsDoNotMatch: 'Heslá sa nezhodujú.',
    usernameTaken: 'Používateľské meno je už obsadené.',
    invalidCredentials: 'Nesprávne používateľské meno alebo heslo.',
    alreadyHaveAccount: 'Máte už účet? Prihláste sa',
    dontHaveAccount: 'Nemáte účet? Zaregistrujte sa',
  },
};